name: Deploy Github Pages

on:
    workflow_dispatch:
    push:
        branches:
            - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        env: 
            MDBOOK_VERSION: 0.4.36
        steps:
            - uses: actions/checkout@v2
            - name: Install mdBook
              run: |
                curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
                rustup update
                cargo install --version ${MDBOOK_VERSION} mdbook

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v4
            
            - name: Build with mdBook
              run: mdbook build
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              run: |
                mkdir -p temp/docs
                cd ./temp
                cp -r ../book/* ./docs/
                git init
                git add -A
                git commit -m 'deploy'
                git push -f git@github.com:masha-note/gfm-translation.git master:gh-pages
                cd -
